-- AlterTable
ALTER TABLE "DraftState"
ADD COLUMN "draftOrderTeamIds" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "currentPickIndex" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "roundNumber" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "direction" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "isDraftActive" BOOLEAN NOT NULL DEFAULT false;
